enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  react-scripts@*:
    dependencies:
      typescript: 4.5.5
  react@*:
    peerDependencies:
      react-dom: "*"

yarnPath: .yarn/releases/yarn-1.22.19.cjs
